### ISSUE TITLE
error checking in update method

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/osqp-python#15]
When making an update to the cost data 'Px' in the 'update' method, the python OSQP interface does not check whether the array that has been passed is the correct size.   If not index set is provided, OSQP should enforce a condition that the Px array provided by the user is the same length as the number of marked non-zeros in the upper triangle of P.

**Comment by bstellato** [comment]
I would perform as many checks as possible from the C interface and setup a return status code to be correctly interpreted from each interface. This is inline with https://github.com/oxfordcontrol/osqp/issues/100

For this issue it might make sense to add the length of `Px` as a parameter of the update functions. I know this would break the API but we can consider it in release `0.6`.
