### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by gshaikov** [oxfordcontrol/osqp-python#33]
I am running the following simple script:
```
import osqp
import numpy as np
from scipy.sparse import csc_matrix

P = np.array([[1,0], [0,1]])
q = np.array([-1,-1])
A = np.array([[1,0], [0,1]])
l = np.array([0,0])
u = np.array([1,1])

P = csc_matrix(P)
A = csc_matrix(A)

settings = {
    'verbose': True,
}

# This works
m = osqp.OSQP()
m.setup(P=P, q=q, A=A, l=l, u=u, **settings)
results = m.solve()
print(results.x)  # [0.99895712 0.99895712]

# This fails with Segmentation fault: 11
results = osqp.solve(P=P, q=q, A=A, l=l, u=u, **settings)
print(results.x)
```
Creating OSQP object and calling a solve method on it works fine.
The value of `x` is [0.99895712 0.99895712].

Direct invocation of `osqp.solve` terminates with Segmentation fault: 11.

Setup:
MacBook Pro, MacOS Mojave 10.14.6
Python 3.7.2
OSQP 0.6.1
numpy 1.16.2
scipy 1.2.2

**Comment by bstellato** [comment]
I just tried your code and it seems to give the segfault when `verbose=True`. Have you tried it with `False` instead? I will look into a fix.

**Comment by sbarratt** [comment]
@bstellato I'm getting a seg fault with `verbose=False` when running 50 in parallel. Here's the code

```
import osqp
import numpy as np
import scipy as sp
from scipy import sparse
from multiprocessing.pool import ThreadPool

def f(i):
    m = 30
    n = 20
    Ad = sparse.random(m, n, density=0.7, format='csc')
    b = np.random.randn(m)

    # OSQP data
    P = sparse.block_diag([sparse.csc_matrix((n, n)), sparse.eye(m)], format='csc')
    q = np.zeros(n+m)
    A = sparse.vstack([
            sparse.hstack([Ad, -sparse.eye(m)]),
            sparse.hstack([sparse.eye(n), sparse.csc_matrix((n, m))])], format='csc')
    l = np.hstack([b, np.zeros(n)])
    u = np.hstack([b, np.ones(n)])

    # Setup workspace
    osqp.solve(P, q, A, l, u, verbose=False)

pool = ThreadPool(4)
pool.map(f, range(50))
```

**Comment by bstellato** [comment]
I think the printing issue was related to this https://github.com/cvxgrp/scs/pull/48 I will try to fix it tomorrow together with your segfault problem.

**Comment by gshaikov** [comment]
@bstellato thank you for the prompt response! You are right, `verbose=False` solved the second case.
