### ISSUE TITLE
Remove dependency on future for Python 3

### ISSUE THREAD

**Issue by wkschwartz** [oxfordcontrol/osqp-python#34]
As I understand it, the [`future` package](https://python-future.org/) has no effect when installed on Python 3, and exists only to allow Python 2 to run Python 3 code. Insofar as OSQP-Python actually relies on any of `future`'s features, it does so only when running on Python 2. Thus, it should be possible to reduce the installation load for Python 3 users by not installing `future` when hosted on Python 3. To do this, all you would need to do is to change
https://github.com/oxfordcontrol/osqp-python/blob/8e009e7dd41c44d1d2c31f92a5a0a035de6fb9f0/requirements.txt#L3
to

```
future;python_version<="2.7"
```
(See [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers).)

**Comment by bstellato** [comment]
This is fixed in #35. Feel free to reopen it in case.
