### ISSUE TITLE
codegen error 

### ISSUE THREAD

**Issue by yonchien** [oxfordcontrol/osqp-python#41]
I used the codegen like this 
![1576806079(1)](https://user-images.githubusercontent.com/37019390/71222812-ef531280-230c-11ea-808b-5356ceb8db02.png)

but it er error at CMakeLists.txt:120 (add_subdirectory):
  The source directory
/home/lyj/code1/include
does not contain a CMakeLists.txt file.
and I found that the CMakeLists.txt not copy to the target_include folder.  I think you have some mistake in codegen.py file

**Comment by gbanjac** [comment]
I have just run your code on my machine and it seems to work fine.

Please provide more details on your OS, Python version, OSQP version, how you installed OSQP etc.

**Comment by yonchien** [comment]
I use linux16.04 ,python 3.5  osqp 0.6.0  I install osqp from the source code

**Comment by goulart-paul** [comment]
When you say "I install osqp from the source code", what did you do specifically?   Did you clone via github, and did you remember to clone submodules?

**Comment by changyunnxp** [comment]
I met same issue, cmake complained the "include/" subfolder under generated code does not contain CMakeLists.txt. 


>CMake Error at CMakeLists.txt:120 (add_subdirectory):
> The source directory

>    xxxxx/code/include

 > does not contain a CMakeLists.txt file.

I installed OSQP by pip. Any ideas? Thanks.

**Comment by zhuyanhao** [comment]
I had the same issue, installed `0.6.1` from conda. There's a file called `osqp` in `include` directory. Have to rename it to `CMakeLists.txt` to make it work.

**Comment by bstellato** [comment]
We just released 0.6.2. Can you please check if that's resolved?

**Comment by jdark-tremor** [comment]
As the (confused) author of issue #48 I can confirm that the pypi 0.6.2 release fixes the codegen error I was observing. That error was identical to the one in this issue.

**Comment by jasondark** [comment]
As the (confused) author of issue #48 I can confirm that my codegen problem, which was identical to the one in this issue, is resolved by the pypi 0.6.2 release of OSQP.

**Comment by bstellato** [comment]
That's great! Thanks for confirming it.
