### ISSUE TITLE
Need a pip release

### ISSUE THREAD

**Issue by r-barnes** [oxfordcontrol/osqp-python#43]
aba0a5fb0afc677ae69aa4cad429237988e91e9f fixes a bug where the `warn` package isn't imported.

Without this, users get unhappy errors like:
```
NameError: name 'warn' is not defined
```

The current pip version, 0.6.1, does not incorporate this fix. A new bugfix version should be released, if possible.

**Comment by bstellato** [comment]
Fixed in #49
