### ISSUE TITLE
Installation fails if numpy is not already installed with python 3.9

### ISSUE THREAD

**Issue by AtsushiSakai** [oxfordcontrol/osqp-python#47]
Thank you for great OSS!!.
I think a similar issue of #40 exists on Python 3.9.

> Collecting osqp>=0.4.1
>   Downloading osqp-0.6.1.tar.gz (211 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zg0bvhs2/osqp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zg0bvhs2/osqp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t6j45zjf
>          cwd: /tmp/pip-install-zg0bvhs2/osqp/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-zg0bvhs2/osqp/setup.py", line 11, in <module>
>         import numpy
>     ModuleNotFoundError: No module named 'numpy'

I think many people are waiting pip wheels for python 3.9!!

**Comment by AtsushiSakai** [comment]
@bstellato Hi. Is it possible to create pip wheels for python3.9? cvxpy has a installation problem because of this issue..

**Comment by bstellato** [comment]
You can find the 0.6.2 release on pypi from #49 .

**Comment by AtsushiSakai** [comment]
I confirmed it works. Thank you so much!!
