### ISSUE TITLE
pypi's 0.6.1 is actually 0.6.0 (probably?)

### ISSUE THREAD

**Issue by jasondark** [oxfordcontrol/osqp-python#48]
I was recently trying the codegen interface and was getting the cmake issue from https://github.com/oxfordcontrol/osqp-python/issues/41

I verified that my installed version was the tagged 0.6.1 release, e.g. `../my/venv/lib/python3.9/site-packages/osqp-0.6.1.dist-info` and was confused, since investigating the source code pertaining to the codegen, the fix from the 0.6.1 release was not present.

Independently, I've also encountered the same issue here: https://github.com/oxfordcontrol/osqp-python/issues/43
That is, the warning module fix that was also part of the 0.6.0 to 0.6.1 bump is also not present. It seems reasonable to conclude that the source for 0.6.0 was uploaded to pypi instead of 0.6.1.

Here is some source code that triggers both these errors, confirmed from a fresh virtual environment in Python 3.9.0 installing only `pip install osqp`
```python
import osqp
import numpy as np
import scipy.sparse as sparse

P = sparse.diags([1, 1]) # add .tocsc() if you want to trigger the codegen error instead of the warn error
q = np.zeros(2)

A = sparse.csc_matrix([[1, 1], [1, 0], [0, 1]])
l = np.array([1, 0, 0])
u = np.array([1, np.inf, np.inf])

model = osqp.OSQP()
model.setup(P=P, q=q, A=A, l=l, u=u)

# Solve the program
results = model.solve()
print(results.x)

# Let's instead codegen it
# https://osqp.org/docs/codegen/python.html
model.codegen("simple_qp")
print("Success!")
```

**Comment by jasondark** [comment]
I was apparently confused. The 0.6.1 release was 39aa8ba, on aug 31. The two fixes above happened on sep 1 and 2nd. Given that, could we get a 0.6.2 release that incorporates those fixes?

**Comment by bstellato** [comment]
You can find the 0.6.2 release on pypi from #49 .
